### PR TITLE
Update 14.x

### PR DESCRIPTION
**Pull request by dogty**

### CODE REVIEW

**Comment by spacemeowx2** [comment]
Thanks, will see try it later

**Comment by spacemeowx2** [comment]
It seems that the actions configuration needs to be updated, let me debug it

**Comment by dogty** [comment]
Out of curiosity where do you get the updated information on how you should set the action configurations? Where do you get the information on how a specific interface works?

**Comment by spacemeowx2** [comment]
A1:

https://github.com/spacemeowx2/devkitpro-action/tree/v2

Just compile it using [act](https://github.com/nektos/act), and fix it by error message..Such as update libnx and toolchain.

A2:
By reverse engineering the ldn service or a specific game with symbols(as far as I know, the first version of Diablo 3 leaked the elf file with symbols), it is possible to infer how the interface works

**Comment by dogty** [comment]
My mistake Ive already updated the actions configuration by fotking your actions you can check my fork if you want.

I was more interested in the re of the interfaces

**Comment by spacemeowx2** [comment]
The reverse part of the job is very boring... One thing I didn't mention is that when I first started writing ldn_mitm, I would use mitm to record the bare bytes of ipc, and then parse it manually....

Simply put, it's a cycle of error, restart, modify, update, and error again

**Comment by dogty** [comment]
That's what I started doing I thought there was maybe some kind of documentation the only thing I found was that https://github.com/kinnay/NintendoClients/wiki/LDN-Protocol#advertisement-frame it gave me a good starting point but I thought there was something else. Thank you!

**Comment by spacemeowx2** [comment]
https://switchbrew.org/wiki/LDN_services#Network_protocol 

Look here too, although you may have already seen it

**Comment by dogty** [comment]
Yes I have but thank you!

**Pull request merged**
