### PR TITLE
Support latest libnx and Atmosphere (1.6.2)

### PR DESCRIPTION
**Pull request by CRC-Mismatch**
Still new to this whole NX homebrew development thing, so I'm not sure if that's all that's needed to properly make it work with FW 17.0 - either way, I did use the already existing GitHub Actions to produce a release artifact, and it "works on my machine :tm: ". But hey, at least it builds :man_shrugging:

### CODE REVIEW

**Comment by CRC-Mismatch** [comment]
Upon further inspection, I didn't update my emuMMC to 17... After updating, it fails to boot :upside_down_face:

**Comment by spacemeowx2** [comment]
Thank you for your PR. Unfortunately, my interests are elsewhere recently, so I can't help with testing and fixing. But I can hit the merge button when it's ready :)

**Comment by torsina** [comment]
I am willing to help get support to this up to fw 18 but not higher as ccp isn't my strong suit. But if you left the repo in this state nobody will ever be able to create new PRs and keep this up to date. You could add @CRC-Mismatch and me as moderators as I'm rebuilding my CFW switch I would be on the lookout for people that want to take part in this community, mayb ask Atmosphere's contributors if some of them are willing to take up the torch as this and [switch-lan-play](https://github.com/spacemeowx2/switch-lan-play) are extremely important for ones of us who like multiplayer (can't wait to play stardew valley with my partner again)

**Comment by lowburger** [comment]
@spacemeowx2 fix very simple... pls merge this PR and update atmosphere lib to latest version and all work fine in latest atmosphere and firmware.

If you like we may test it before move to release.

**Comment by spacemeowx2** [comment]
@CRC-Mismatch Hi, can you remove the draft tag so I can merge it?

**Pull request merged**
